### ISSUE TITLE
Replace "From" header, even if present

### ISSUE THREAD

**Issue by andornaut** [marlam/msmtp-mirror#10]
Please considering offering an option to replace email "From" headers, even if present.

This option would support use cases such as:

Vixie Cron sets a "From" header of "root (Cron Daemon)", which is rejected by Gmail with an error "Messages missing a valid address in From: header, 5.7.1 or having no From: header, are not accepted". I believe that Gmail only accepts emails with "From" headers in the form "name <name@example.com>".

I do not believe that Vixie Cron can be configured to use a different "From" header. Searching the web turns up workarounds such as filtering emails through a script before passing them to msmtp (see [answers to this servervault question](https://serverfault.com/questions/438843/how-to-customise-email-headers-from-vixie-cron-debian-and-msmtp)). Of course, I could try to find an alternative to Vixie Cron or an alternative to Gmail, but it'd be great if msmtp could support a "From" header override.

Perhaps a configuration option: ‘replace_from_header [(on|off)]’?

**Comment by marlam** [comment]
I can see why something like that will be useful because of DMARC and other anti-spam measures, not just for Gmail.

I'm not yet sure how the option should work. Maybe `remove_original_from_headers [(on|off)]`, which together with the existing `add_missing_from_header` (on by default) would effectively replace the From header?

**Comment by andornaut** [comment]
> Maybe remove_original_from_headers [(on|off)], which together with the existing add_missing_from_header (on by default) would effectively replace the From header

IMHO I don't think that is ideal, b/c it requires that the configuration options be understood to apply in a particular order - at least for it to achieve the desired end. Consider:

| applied first | applied second | replaced?
--- | --- | ---
`remove_original_from_headers` | `add_missing_from_header` | yes
`add_missing_from_header` | `remove_original_from_headers`| no

Additionally, the meaning of "missing" in `add_missing_from_header` would become somewhat ambiguous in the context of `remove_original_from_headers`. Should a header be considered "missing" if msmtp is the one that removed it? Perhaps so, but users could reasonably infer the opposite.

I think that this could be improved by removing the ordering dependency:

| applied first | applied second | replaced?
--- | --- | ---
`replace_from_header` | `add_missing_from_header` | yes
`add_missing_from_header` | `replace_from_header` | yes

`replace_from_header` would default to "off" as it obviates `add_missing_from_header` when enabled.

I would be happy with any solution, though. I appreciate your time and consideration!

**Comment by marlam** [comment]
Thanks for your input. Maybe there is another way: combine both options into one, e.g. `set_from_header (on|off|auto)` where off means never, on means always, and auto means only if there is no From header.
The existing `add_missing_from_header` could be kept for compatibility, and would set this to either `off` or `auto`.
For consistency, `add_missing_date_header` should probably be renamed in the same way, but it would not offer an `on` option as that seems unnecessary.

What do you think?

**Comment by andornaut** [comment]
I like it!

**Comment by marlam** [comment]
OK, I pushed this change. Works in my tests.

**Comment by andornaut** [comment]
I tested this change, and it works great. Thanks!
