### ISSUE TITLE
msmtp_print_conf should include allow_from_override setting

### ISSUE THREAD

**Issue by nbriggs** [marlam/msmtp-mirror#100]
I'm having the same problem as described in issue #51 and in trying to debug it, using msmtp version 1.8.20 on a FreeBSD box, I found that the debugging output does not show the setting of the allow_from_override configuration option when it is dumping the configuration in `msmtp_print_conf()`.

**Comment by marlam** [comment]
Thanks for pointing this out, this is fixed now.
