### ISSUE TITLE
Automatic yes to prompts install option broken

### ISSUE THREAD

**Issue by cunum** [marlam/msmtp-mirror#101]
I'm using msmtp inside a docker container. The docker build is broken since today because the "Automatic yes to prompts" install option doesn't work anymore:

`apt install -y msmtp` on debian buster leads to an input prompt like this:

<img width="565" alt="Bildschirmfoto 2022-10-04 um 20 20 32" src="https://user-images.githubusercontent.com/26085773/193896394-afe7ceb3-9bd8-43a7-9b1f-f04da09c17ce.png">

**Comment by marlam** [comment]
This is a problem of the Debian package, not of msmtp itself. Please use the Debian bug tracker.
