### ISSUE TITLE
Follow the XDG base directory specification

### ISSUE THREAD

**Issue by pidario** [marlam/msmtp-mirror#105]
I apologize in advance if the issue has already been opened by somebody else but I couldn't find anything on this bug tracker and furthermore I'm one of those freaks who prefer a de-cluttered home directory. ;-)

Instead of saving config file in `$HOME/.msmtprc`, `${XDG_CONFIG_HOME:-$HOME/.config}/msmtprc` should be used for unix-based operating systems according to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

As well as keeping the home directory clean, the semantic separation of config, runtime data, cache data and user-local software by the spec is helpful to users and other tools (e.g. backup software).

In terms of migration, I would suggest using the xdg-compilant config location if it exists and falling back to the current default location.

I know someone could decide to run msmtp with the `-C` or `--file` switch in order to read from a different configuration file but I feel the XDG base directory specification is a nice default behavior.

**Comment by marlam** [comment]
This is supported since version 1.6.7 (June 2018) and it's documented in the manual and in the man page.

**Comment by pidario** [comment]
I feel so ashamed... Apologies for my complete lack of thoroughness... Today is not the first time I don't read the F**** Manual..
And I believe @dariuskramer didn't as well. :)
A simple google search would have produced [this](https://github.com/marlam/msmtp-mirror/commit/af2f409) but as you said it's also in man.
I hate myself. Apologies again.
