### ISSUE TITLE
msmtp-queue: -v unary operator expected

### ISSUE THREAD

**Issue by janedenone** [marlam/msmtp-mirror#106]
Hi,

I just tried using msmtpq / msmtp-queue with the following setup

```
# .zshrc
export Q='/Users/snafu/MailQueue'
export LOG='/Users/snafu/msmtpq.log'
```

Messages are queued correctly, but when I run `msmtp-queue -d`, the messages in the queue are displayed along with an error message:

```
/opt/homebrew/bin/msmtpq: line 88: [: -v: unary operator expected
```

This error message occurs with or without the LOG environment variable in `.zshrc`, and the log is always written to the default path (`/Users/snafu/log/msmtp.queue.log`). What am I doing wrong?

Thanks, Jan

**Comment by marlam** [comment]
The msmtpq script does not have a maintainer right now, and I don't use it myself. The problem seems to be related to the shell running the script. But that should always be bash; maybe it's a bash version problem?

**Comment by janedenone** [comment]
Yes, it is probably related to some bash/zsh specific syntax, but I have not been able to fix it (unlike the incorrect ping parameter in `connect_test()`). I will just have to live with an unconfigurable log file location. Thanks for looking into this!
