### ISSUE TITLE
Missing support for user %U

### ISSUE THREAD

**Issue by hdante** [marlam/msmtp-mirror#107]
Hello, currently msmtp doesn't seem to support "user %U":

	[hdante@dragonmount ~]$ cat /etc/msmtprc 
	defaults
	auth on
	tls on
	tls_starttls off
	port 465
	syslog LOG_MAIL
	set_from_header on

	account default
	host smtp.gmail.com
	from %U@gmail.com
	user %U
	[hdante@dragonmount ~]$ sendmail hdante@gmail.com
	Test.
	password for %U at smtp.gmail.com: 
	sendmail: authentication failed (method PLAIN)
	sendmail: server message: 535-5.7.8 Username and Password not accepted. Learn more at
	sendmail: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials 16-20020a1f1710000000b003bbea0bf38bsm568681vkx.56 - gsmtp
	sendmail: could not send mail (account default from /etc/msmtprc)

Expected message would be: "password for hdante at smtp.gmail.com".

Is it possible to add this feature ? Thanks,

**Comment by marlam** [comment]
It would be possible but I'm not sure if it's worth it. You can probably achieve something similar with the `eval` command, e.g. `eval echo user $USER`.

**Comment by kkarsten62** [comment]
I would like to substitute all email addresses by variable by the above mentioned `eval` option.

I enter in `/etc/msmtprc`
`eval echo account $MY_EMAIL_ADRESS`

Start container:
`$ docker exec -it my_container /bin/bash`
`$ echo "Test email" | mail -s "A test mail from the container" user@mydomain.tld`
I get:
```
msmtp: /etc/msmtprc: line 21: unknown command eval
mail: Sending data to /usr/bin/msmtp -t failed: Process exited with a non-zero status
mail: cannot send message: Process exited with a non-zero status
```
When entering:
`eval echo account user@mydomain.tld`
I get same error message

When entering:
`account user@mydomain.tld`
==> E-Mail is sent correctly

`$ eval echo $ADMIN_EMAIL_ADRESS`
gives
`user@mydomain.tld`

Any idea how to solve it?

**Comment by marlam** [comment]
The `eval` command was added in 1.8.21. You probably have an older version.

**Comment by kkarsten62** [comment]
Thanks.
I am using Docker Image `php:7.4-fpm` based on `Debian GNU/Linux 11 (bullseye)` with `msmtp version 1.8.11`.
This seems to be the reason.
I will try to update soon.
