### ISSUE TITLE
mails are lost if sending fails

### ISSUE THREAD

**Issue by error27** [marlam/msmtp-mirror#109]
I am using msmtp with mutt.  I'm using gmail oauth2.

With my setup, I have to re-log in via a web browser every week.  If I haven't logged in, then my outgoing emails are silently dropped.  Or today there seemed to be some kind of networking issue and all my outgoing emails sent between 10:00 and 11:30 were dropped.

How do I fix this?

**Comment by marlam** [comment]
Msmtp returns an error code when sending a mail fails. Make sure that this error code is not ignored by whatever program is calling msmtp in your setup.
You could also try msmtpq to first queue the mails and send them later.
