### ISSUE TITLE
Disabling delivery 

### ISSUE THREAD

**Issue by flaushi** [marlam/msmtp-mirror#113]
Is it possible to disable the delivery of mails ?

The sendmail calls however should still return successfully. My usecase is a testing environment where I do not want to send mails from. However the software I am testing will require a valid sendmail.

Thanks a lot in advance!

**Comment by marlam** [comment]
There's no such switch in msmtp, but you can simply call a debug script instead of msmtp, e.g.:
```
#!/bin/bash
echo "$@" > /tmp/maildump-header
cat >> /tmp/maildump-body
```
The software won't be able to tell the difference.
