### ISSUE TITLE
Support for Display Name in configuration for from

### ISSUE THREAD

**Issue by psztoch** [marlam/msmtp-mirror#118]
msmtp can add FORM to mail. Both in the message and in the envelope.
But it can't do that with a nice display name.

Of course, the display name should be omitted when used as an envelope from as the RFC says so.
You can't specify -F everywhere. There is a big need to enforce this from configuration.

**Comment by marlam** [comment]
OK, I added a new configuration command `from_full_name` that does what `-F` does. Please test. The change should appear on the github mirror in a few hours.

**Comment by psztoch** [comment]
I looked at the code on your git and it looks ok.
Sorry, I can't test it right now.

There is another related problem with `set_from_header`
Default value *auto* is very good, but it can't handle broken apps that put stupid stuff into the FROM field.
The setting for list or regexp of forbidden FROM entries is very much missing.
If from is present and match this list, they would be replaced (as in the case of `set_from_header on`).

In example:
"Anacron <root>"
"root (systemd-cron)"
"root"

Of course, some problems with the FROM field are due to older versions of these applications, but they are not always easy to update. It would be nice to be able to solve them from the msmtp configuration level.

**Comment by marlam** [comment]
Hm, I'm not convinced that level of configurability is worth the effort. I think `set_from_header on` is just fine in that case.
