### ISSUE TITLE
Version 1.8.8  compile error with gettext version .20   on Debian 9

### ISSUE THREAD

**Issue by lachlanA** [marlam/msmtp-mirror#12]
Compile error is
make[2]: Entering directory '/home/laudas/src/msmtp/build/po'
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.19 but the autoconf macros are from gettext version 0.20
Makefile:188: recipe for target 'stamp-po' failed

     Changing the macro in "po/Makefile.in.in" to 0.20

     # Origin: gettext-0.19.8
      GETTEXT_MACRO_VERSION = 0.20

 Fixs the problem,    I can send mail !! 

Lachlan

**Comment by marlam** [comment]
I fixed this by updating all gettext infrastructure files to 0.20.2.
This will cause problems with gettext 0.19.*, but 0.20 is out for a while now and we have to switch at some point anyway.
