### ISSUE TITLE
Using a ENVVar for logfile

### ISSUE THREAD

**Issue by LiamKearn** [marlam/msmtp-mirror#122]
Is this possible? It doesn't seem so with testing. I also can't see anything grepping https://marlam.de/msmtp/msmtp.html#Authentication for 'env'.

eg. I would like to use:
```
logfile $LOG_HOME/msmtp/log
```

I define `$LOG_HOME` based on uname.

Thanks :)

**Comment by marlam** [comment]
Yes, it works with the `eval` command:
```
eval echo logfile $LOG_HOME/msmtp/log
```

**Comment by LiamKearn** [comment]
> Yes, it works with the `eval` command:
> 
> ```
> eval echo logfile $LOG_HOME/msmtp/log
> ```

Ah, I only searched the arch wiki for 'eval' specifically because I guessed the terminology would be reused from 'passwordeval' 🙂 

Just found [your proper documentation site](https://marlam.de/msmtp/msmtp.html)
