### ISSUE TITLE
msmtpd authentication does not work with mutt

### ISSUE THREAD

**Issue by mbakhterev** [marlam/msmtp-mirror#125]
Mutt, when sending message, will try to PLAIN authenticate with message of the form `user\0user\0password` which is not accepted by msmtp. Msmtp itself authenticates with message `\0user\0password`, and it works with msmtpd. It seems both Mutt and msmtpd behave accordingly to RFC 4616. But may be msmtpd should tolerate non-empty "authorization identity"?

-- Respectfully Mike

**Comment by marlam** [comment]
This should be fixed now with the commit mentioned above; can you test it?

**Comment by mbakhterev** [comment]
It works now. Thanks!
