### ISSUE TITLE
configure - syntax error near unexpected token libgnutls

### ISSUE THREAD

**Issue by drhirn** [marlam/msmtp-mirror#135]
Using Ubuntu 22.04.3 I get the following errors when running `configure`:

```
./configure: line 9154: syntax error near unexpected token `libgnutls,'
./configure: line 9154: `    PKG_CHECK_MODULES(libgnutls, gnutls >= 3.4, HAVE_LIBGNUTLS=1, HAVE_LIBGNUTLS=0)'
```

Package `libgnutls-dev` isn't available in my Ubuntu-release, so I installed `libgnutls28-dev`. May this be the reason?

Tried master branch and 1.8.24.

**Comment by marlam** [comment]
I suspect it does not understand `PKG_CHECK_MODULES` because `pkg-config` is missing. Does it work if you install `pkg-config` and rerun `autoreconf`?

**Comment by drhirn** [comment]
It does! Thanks a lot.

Maybe add this to the instructions on https://marlam.de/msmtp/download/?

**Comment by marlam** [comment]
Thanks for testing, I added `pkg-config` to the list of packages on https://marlam.de/msmtp/download/
