### ISSUE TITLE
full-name in From: header

### ISSUE THREAD

**Issue by atesin** [marlam/msmtp-mirror#136]
hi...  this is more like a question or suggestion (is there a forum or community section here in girhub repo?)

in msmtp... **how can i add a From; header with full name like `From: "J. Random Bot" <jrbot@automail.pub>`?**

... with "from" command?, with "set_from_header"?.... if possible, could you also add this feature in documentation please?

--
**situation**: imagine somebody bought a single smtp account somewhere, and uses this same account with msmtp and many profiles, to send messages for different things like: his forum, his contact form, his home alarm system, etc....

until same address in from header and envelope, a good way to distinguish source and sort messages could be the From: header with full name, like
```
From: "J. Random Forum Notifications" <jrbot@automail.pub>
From: "J. Random Contact Form Message" <jrbot@automail.pub>
From: "J. Random Home Alarm System" <jrbot@automail.pub>
From: "J. Random Joke of the day" <jrbot@automail.pub>
...
```

**Comment by marlam** [comment]
You can use `from_full_name YOUR_NAME` to set the full name in the From header that msmtp creates.

Note that msmtp only creates the From header if the mail does not have one yet or you use `set_from_header on`.

**Comment by traeu** [comment]
Is the option "from_full_name" new?
I am using version 1.8.16 on ubuntu 22.04 LTS and I get the error 
"/etc/msmtprc: Zeile 17: Unbekannter Befehl from_full_name". 
Is there any other way to configure the default full-name in MSMTP's config file?

**Comment by atesin** [comment]
> Is the option "from_full_name" new? I am using version 1.8.16 on ubuntu 22.04 LTS and I get the error "/etc/msmtprc: Zeile 17: Unbekannter Befehl from_full_name". Is there any other way to configure the default full-name in MSMTP's config file?

yes is fairly new, i haven't in my system either (openwrt)... but maybe you could use grep/cat/etc to "inject" a from_full_name smtp header, or write a wrapper, until is hard and annoying tough
