### ISSUE TITLE
Listen to several interfaces

### ISSUE THREAD

**Issue by azmeuk** [marlam/msmtp-mirror#138]
I have been meeting a situation where I would have loved if msmtp listened on several interfaces.

I have a cluster of hypervisors. They have proprietary management interfaces (HP iLO, Dell IDRAC) that are plugged on a private offline network. The hypervisors OSes are connected to both this offline network and another online network, so they can go on the internet.

I would like to configure the management interfaces to send alert mails (on hardware failure for instance). As they are offline, they must use a mail relay to actually send the mails.

Thus, I would like to install msmtp on the hypervisors, and make it listen to that offline network interface. However, I would like to not unplug msmtp from `127.0.0.1` so local process can still send mails.

I suggest allowing msmtp to listen on several interfaces.

What do you think?

**Comment by marlam** [comment]
Yes, msmtpd could be extended to be able to listen on multiple interfaces.
In the meantime, you can work around this by simply starting multiple instances of msmtpd, one for each interface.
