### ISSUE TITLE
Placing emails that could not be sent on a named queue

### ISSUE THREAD

**Issue by lenormf** [marlam/msmtp-mirror#17]
Hi,

Is it possible to place emails that could not be sent for temporary reasons (4XX error codes) on a named queue, so that `msmtp` could try re-sending them later on?

Thanks!

**Comment by marlam** [comment]
No, that is not possible. You could write a script that does this based on the msmtp exit code (see `sysexits(3)`), but really, this is probably better handled by using postfix.

**Comment by lenormf** [comment]
Wouldn't you consider support for something very basic? "Add this to a queue" and "process the queue". I'd rather not have to handle storing emails with a wrapper.

**Comment by marlam** [comment]
The existing `msmtpq` script might already do what you want, or can be changed to do it with little work. But such a feature will not go into `msmtp` itself, to keep it simple and small.

**Comment by lenormf** [comment]
I wasn't aware of that script, it looks like what I need, thanks!

**Comment by lenormf** [comment]
For reference, I didn't find out those scripts existed because (from ArchLinux's package manifest):

```
# Installing example configs and scripts to /usr/share/doc/msmtp
# as they are not installed by default (Debian and Gentoo do it this way)
```

I think executable scripts supported in this repository should be deployed to `$PREFIX/bin`, what do you think? It would really take the maintainer of `msmtp` itself to convince all three distros at once :)
