### ISSUE TITLE
passwordeval consumes stdin (truncates emails)

### ISSUE THREAD

**Issue by darlo-me** [marlam/msmtp-mirror#18]
Hey, I have been using msmtp to forward my mails and noticed that some programs will consume stdin (or close it?), which breaks sending emails.

Reproduce:
- set passwordeval to `ssh localhost 'echo password'`
- cat mail | msmtp [...] # where mail is bigger than 4097 bytes (which seems related to the pipe buffer/page size?)
- Notice a log like the following:
`msmtp: host=[...] tls=on auth=on user=[...] from=[...] recipients=[...] mailsize=4097 smtpstatus=250 [...]`
- Recipient receives truncated message

The mailsize truncating might happen at a different size. I tested on Linux 5.5.5. This also does not raise any error, but truncates the email.

My quick analysis:
Looks like passwordeval is using popen() to spawn the subshell, which inherits stdin if "w" is not specified in the type argument.

My guess is:
- msmtp spawns ssh
- ssh closes the pipe before it exits
- pipe process end from pipe close
- msmtp tries to read from the pipe and reads only up to pipe buffer size before getting end of pipe

I will look into fixing this if I get the time, but this bug isn't that critical since the problem can be worked around by forcing the subshell to use a different stdin (e.g. ssh < /dev/null or ssh -n)

**Comment by marlam** [comment]
I actually don't consider this a real problem; it does not make much sense to use a stdin-consuming process in passwordeval, does it? This was never a problem before, and passwordeval has been around for more than 9 years now.

**Comment by totony-misc** [comment]
It's not as much as it is critical, more so that, when it happens, it is very hard to pinpoint, as:
- it is intermittent (mostly happens for attachments)
- seems to only apply to piped input
- does not produce any error
- you do not know which command open() and close() their stdin (or even that passwordeval could cause this)

Hopefully this github issue helps to diagnose this if it happens to someone else

**Comment by darlo-me** [comment]
It's not as much as it is critical, more so that, when it happens, it is very hard to pinpoint, as:
- it is intermittent (mostly happens for attachments)
- seems to only apply to piped input
- does not produce any error
- you do not know which command open() and close() their stdin (or even that passwordeval could cause this)

Hopefully this github issue helps to diagnose this if it happens to someone else

**Comment by marlam** [comment]
I agree that this is a nasty problem if it happens. Unfortunately I see no workaround except to reimplement `popen()` using low-level system calls, and that would probably open a new set of problems.
So I added a warning to the man page and manual instead, and mentioned the `</dev/null` workaround.
