### ISSUE TITLE
Invalid TLS?

### ISSUE THREAD

**Issue by jarbus** [marlam/msmtp-mirror#23]
I'm trying to send an email from an institutional email account. I use TLS with two google accounts with no issues, however when I try to use my *.edu email to send, I get the following error:

`msmtp: TLS certificate verification failed: certificate 2 of 4 has expired
msmtp: could not send mail (account school from /home/USER/.config/msmtp/config)`

This comes from running: `echo 'hello world' | msmtp -a school address@gmail.com`

My config file is as follows:
```
defaults
auth on
tls on
tls_starttls off
tls_trust_file	/etc/ssl/certs/ca-certificates.crt
logfile	~/.config/msmtp/msmtp.log

account school
host mail.school.edu
port 465
from user@school.edu
user user
passwordeval "pass mutt-wizard-school"```

Is there something I'm missing?

**Comment by marlam** [comment]
The configuration of the mail server uses a certificate chain in which one certificate is expired. So the problem is on the server side, not on your side. Report this to the administrators of the mail server.
