### ISSUE TITLE
Mail delivery fails if server does not support DSN

### ISSUE THREAD

**Issue by kdkasad** [marlam/msmtp-mirror#24]
I like to get mail delivery confirmations, so I have mail DSN enabled in my e-mail client (neomutt). When I send an email to a server that does not support DSN, msmtp fails to send the mail.

It passes this argument to msmtp:
```
-N delay,failure,success
```

Is there a way to make it silently continue?

**Comment by marlam** [comment]
No, and I don't think there should be. Instead of telling Mutt about DSN, you can configure DSN for each mail server in msmtprc, and enable it only where it is supported.

**Comment by kdkasad** [comment]
> you can configure DSN for each mail server in msmtprc, and enable it only where it is supported.

Only after reading this sentence did I realize that DSN support is a problem with the sender's (my) server, not the recipient. Thanks!
