### ISSUE TITLE
Permission error passwordeval and awk

### ISSUE THREAD

**Issue by averter** [marlam/msmtp-mirror#26]
Hello,

I don't know where else to ask for help with an issue that I'm having with msmtp. Basically, for some reason I get a permission error when using passwordeval. I've opened a question on [SO](https://stackoverflow.com/questions/62838673/awk-permission-denied-when-run-through-msmtp), tried lots of things, but got no answer/result so far. Can you please help me or point me towards someone who might be able to help? Thank you in advance.

**Comment by marlam** [comment]
Inexplicable 'permission denied' errors are often caused by an overly restrictive AppArmor profile for msmtp.

Unfortunately this often happens on Debian and Ubuntu and it confuses many users.

**Comment by averter** [comment]
Thank you very much for that. After disabling the apparmor profile for msmtp it worked, and I've learned something new out of this. Probably this happened because in my new OS version they have become more stringent with msmtp? Regardless, you have my thanks. If you can/want to answer my question on SO I will happily accept it/give you the points the question is worth. The commands I've used are
```` bash
sudo ln -s /etc/apparmor.d/usr.bin.msmtp /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/usr.bin.msmtp
````

**Comment by marlam** [comment]
I'm not on SO; if you could add the solution there it might help people finding the problem faster.
