### ISSUE TITLE
"no recipients found" when no To but BCC in headers

### ISSUE THREAD

**Issue by Synchro** [marlam/msmtp-mirror#29]
I'm trying to use msmtp 1.8.12 on macOS to point [PHP's mail() function](https://www.php.net/manual/en/function.mail) at.

If I have no To recipients (the `$to` param to `mail()` is an empty string or `null`), but BCCs are in headers, msmtp fails saying `msmtp: no recipients found`. My message looks like:

```
Date: Tue, 8 Sep 2020 09:06:13 +0000
From: Joe User <user@example.com>
Bcc: joe@example.org
Message-ID: <SOYrHCe9QZFo7Cir8U07mEtQkgOWW9aiCW9JxhiCEpo@Octoo-en0.lan>
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
To: undisclosed-recipients:;
Subject: test

test
```

My msmtp config is:

```
defaults
account helo@mac.local
host localhost
port 2500
auth plain
user test
password password
tls off
undisclosed_recipients off
read-recipients
```

As far as I can see, `read-recipients` should make msmtp use the addresses from the bcc header. I don't want it to set `undisclosed-recipients` for me as I'm doing that myself, so I disabled that.

The same message relayed via postfix's sendmail works as expected. Have I missed something or is this a bug?

**Comment by marlam** [comment]
`read-recipients` is not something that the `.msmtprc` file understands. It is only available as an option, so make sure PHP uses `--read-recipients` (or `-t`) when it calls msmtp.
To test your config, you can use `msmtp --debug --serverinfo`; this should reject your config file because of the `read-recipients` entry.

**Comment by Synchro** [comment]
Ah, thanks, you're quite right – I had omitted the `-t` option when changing my `sendmail_path` PHP config property.
