### ISSUE TITLE
set_from_header not working

### ISSUE THREAD

**Issue by msafadieh** [marlam/msmtp-mirror#31]
I've been trying to setup msmtp to automatically rewrite the `from` headers for my cron emails. I put `set_from_header on` in my config file per the documentation but it seems like `sendmail` is ignoring that.

This the log output. As you can see the `from` header is different than the one in the config file.

```
Sep 26 09:51:02 host=smtp.purelymail.com tls=on auth=on user=log@mhmd.sh from=mhmd recipients=[REDACTED] smtpstatus=530 smtpmsg='530 5.7.1 You (log@mhmd.sh) are not authorized to send mail as mhmd@purelymail.com' errormsg='envelope from address mhmd not accepted by the server' exitcode=EX_DATAERR
```

This is my config:
```
account status
host    smtp.purelymail.com
port    587
from    log@mhmd.sh
user    log@mhmd.sh
password password
tls on
auth on
set_from_header on
logfile ~/.cache/msmtp.log
tls_trust_file /etc/ssl/certs/ca-certificates.crt

aliases /etc/aliases
account default : status
```

**Comment by marlam** [comment]
I cannot reproduce this error, it works for me.
Can you provide a `--debug` output for a small example mail?
(Be sure to remove authentication lines).

Something like
`echo -e "From: wrong@address\nSubject: Test Header\n\nTest Body" | msmtp --debug recipient@example.com`

**Comment by msafadieh** [comment]
That seems to work fine. I was able to fix the issue by telling cron to use `msmtp -t` instead of `sendmail` as instructed on the [ArchWiki](https://wiki.archlinux.org/index.php/cron#Example_with_msmtp).
