### ISSUE TITLE
Flag to bypass the security check

### ISSUE THREAD

**Issue by drzraf** [marlam/msmtp-mirror#35]
When running, `get_conf` does a `check_secure` on the configuration file which fails if:
- `statbuf.st_uid != geteuid()`
- `statbuf.st_mode & (S_IXUSR | S_IRGRP | S_IWGRP | S_IXGRP | S_IROTH | S_IWOTH | S_IXOTH)` (anything > 0600)

I'm using an `/etc/msmtprc` file which could be very well used in the following context:
- `msmtpd` (On Debian, a `{DynamicUser}` systemd daemon part of the `msmtp` group)
- Raw sendmail (actually using [smailq](https://github.com/shuber2/smailq)) which could very well be ran via a PHP-FPM thread or a PHP-cli user
- A cron job

In this context I found *no* permission check that would bypass all these constraints, the main one being the check done by `msmtp` itself. As many other software (like `ssh` or `composer`), I think it deserves a flag to disable this security check.

Note: Relying on msmtpd (as an intermediary socket would securely centralize the access to the rc file) would resolve this but its use is not advised (as per documentation) and the daemon does not support pipelining.

**Comment by marlam** [comment]
The `check_secure` thing is never used on system-wide configuration files (like your `/etc/msmtprc`) and it is only used on user configuration files if they contain passwords. So it does not apply to your situation. Do you specify `/etc/msmtprc` with `-C` or `--file`, thereby making it a user configuration file?

**Comment by drzraf** [comment]
> Do you specify `/etc/msmtprc` with `-C` or `--file`, thereby making it a user configuration file?

Yes, that was it !
(By the way, I still think making it optional may be useful under some circumstances)
