### ISSUE TITLE
msmtp and libressl

### ISSUE THREAD

**Issue by Vouivre** [marlam/msmtp-mirror#37]
Hello,

I'm the maintainer of the package `msmtp` for the KISS linux distribution. As you recommend it, `msmtp` is built with `gnutls`. 

`libressl` is in the official repositories of the distribution and I would like to know your opinion about using `libressl` instead of `gnutls`. I have built `msmtp` with `libressl` and it builds fine. But it's recognized as `openssl`. From the website I know the support of `openssl` could be dropped and probably by the way the support for `libressl`. 

Is it better to keep `gnutls` or is `libressl` also a good choice ?

**Comment by marlam** [comment]
Hi!

Currently GnuTLS is definitely the better choice.

The OpenSSL support in msmtp uses the old OpenSSL API, regardless of whether it is provided by OpenSSL or LibreSSL. That code is currently unmaintained and will probably be dropped at some point.

In the future, we might add support for the modern libtls API provided by LibreSSL. If and when that happens, LibreSSL will be a reasonable alternative to GnuTLS for msmtp.

**Comment by Vouivre** [comment]
Thank you for your answer, it answers perfectly my question!

**Comment by marlam** [comment]
An update: msmtp now supports libtls from the LibreSSL project. This code is new, but already full featured. It is a reasonable alternative to GnuTLS, but the latter is still the default.
