### ISSUE TITLE
Connect timeout four times that specified in config file?

### ISSUE THREAD

**Issue by dtgriscom** [marlam/msmtp-mirror#38]
I'm testing code that drives msmtp, and would like the code to fail gracefully. One scenario is if the user enters the wrong port number, and the server never responds; I don't want msmtp to wait forever, so I'm specifying a `timeout` value.

Problem: the actual timeout seems to be four times the value specified in the configuration file. Specify 30 seconds, msmtp takes 120 seconds to fail. Specify 10 seconds, msmtp takes 40 seconds to fail. (This is with a non-TLS connection to port 25, where the specific server doesn't support port 25, BTW.)

Why does msmtp take four times as long as specified? Alternatively, what's a reasonably low timeout value I could use that wouldn't cause connection failurs?

Version output:
````
$ msmtp --version
msmtp version 1.8.13
Platform: i686-pc-linux-gnu
TLS/SSL library: none
Authentication library: built-in
Supported authentication methods:
plain external cram-md5 login oauthbearer xoauth2 
IDN support: enabled
NLS: enabled, LOCALEDIR is /usr/local/share/locale
Keyring support: none
System configuration file name: /usr/local/etc/msmtprc
User configuration file name: /home/devuser/.msmtprc

Copyright (C) 2020 Martin Lambers and others.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
````

Config file:
````
defaults
auth on
tls ${tlsFlag}
tls_trust_file /opt/tools/etc/ca-certificates.crt
logfile ${logfile}

account sender
host ${serverName}
port ${portNum}
user ${user}
from ${fromUser}
password ${password}

timeout 10

account default : sender
````

**Comment by marlam** [comment]
I cannot reproduce the problem here, the timeout works as intended. Could this be something specific to your system or network setup?

**Comment by dtgriscom** [comment]
Very possibly so. What should I look for?

**Comment by marlam** [comment]
I don't know. Can you test with `localhost`, to determine if it's the system or the network?

**Comment by dtgriscom** [comment]
Understood: sorry I haven't been able to give more information on this. Will reopen when (if) I can give more info.
