### ISSUE TITLE
Tilde (~) is not replaced by $HOME in Neomutt

### ISSUE THREAD

**Issue by jt0in3e** [marlam/msmtp-mirror#39]
A command `/usr/bin/msmtp -C ~/.config/msmtp/config -a main` doesn't work within Neomutt (_neomuttrc_ config) displaying error `File or directory not found`.
Replacing **~** with **$HOME** works as expected. 

**neomutt** _version_: 20200925

**msmtp** _version_: 1.8.13

**Comment by marlam** [comment]
There is nothing msmtp can do about this. The tilde expansion, just like expansion of environment variables, happens before msmtp is even started.

**Comment by jt0in3e** [comment]
@marlam Is it possible to mention somewhere in the docs of such a case? 
Maybe in the example for Neomutt.
I've spent a lot of time trying to figure out why neomutt won't sent mails with msmtp. It is not obvious that such an expansion is made before msmtp runs and not by msmtp.
