### ISSUE TITLE
5.4.4 error - All email bounces back to the sending account email

### ISSUE THREAD

**Issue by themew** [marlam/msmtp-mirror#42]
Debian 10 install on server without any email installed.  Sending email using msmtp and CLI delivers and works great.

However, email sent from the panel (HestiaCP) to notify me of issues delivers to the account being used to authenticate msmtp and shows undeliverable to the receiving address.

`Reporting-MTA: dns; mail.sendingdomain.com
X-Postfix-Queue-ID: 14130238EB
X-Postfix-Sender: rfc822; email@sendingdomain.com
Arrival-Date: Sun, 24 Jan 2021 18:40:57 -0600 (CST)

Final-Recipient: rfc822; email@receivingdomain.com_
Original-Recipient: rfc822;email@receivingdomain.com_
Action: failed
Status: 5.4.4
Diagnostic-Code: X-Postfix; Host or domain name not found. Name service error
    for name=receivingdomain.com_ type=AAAA: Host not found`

So the email comes through to me at the sending domain as a bounce (undeliverable).

**Comment by marlam** [comment]
Sorry that's not enough information for me to be able to help you. I have no idea what HestiaCP is; maybe this has to do with its configuration. Also that 'host not found' error does not seem to originate from msmtp.

**Comment by marlam** [comment]
Closing this because of lack of information.
