### ISSUE TITLE
Substitution in envelope "from" not working

### ISSUE THREAD

**Issue by sickill** [marlam/msmtp-mirror#47]
I put this in the system-wide config file (`/etc/msmtprc`):

```
from %U@%H
``` 

and when I'm trying to send email with `msmtp` (also with `sendmail` command) I'm getting the error from the SMTP server:

```
msmtp: envelope from address %U@%H not accepted by the server
msmtp: server message: 501 <%U@%H>: domain missing or malformed
msmtp: could not send mail (account default from /etc/msmtprc)
```

I tested with user config file `~/.msmtprc` and getting the same result.

---

msmtp version: 1.8.6 (Ubuntu 20.04)

---

I've found out that someone else is having the same issue with msmtp 1.8.3 on Debian: https://serverfault.com/questions/1054731/msmtp-sendmail-substitutions-dont-work-u-etc

**Comment by marlam** [comment]
The `%U` pattern was introduced in version 1.8.7 (along with `%H`, `%C`, `%M`).
In simple cases you might be able to use the old `auto_from` command instead.

**Comment by sickill** [comment]
Got it. Thanks for the clarification and sorry for the noise.
