### ISSUE TITLE
Encrypt emails

### ISSUE THREAD

**Issue by Gooberpatrol66** [marlam/msmtp-mirror#49]
Is there a way to encrypt emails (say with gpg) before transferring them so that the mail server cannot read them?

**Comment by marlam** [comment]
That has to be done outside msmtp. Msmtp just sends the mail; its construction including encryption is the task of the mail user agent (MUA).

**Comment by Gooberpatrol66** [comment]
So if I have programs on my server that only support sending unencrypted logs to email addresses, is there a way to encrypt them before msmtp sends them to a 3rd-party email server? Or do I have to find something else to use?

**Comment by marlam** [comment]
Pipe them through some other program that handles the encryption before handing them over to msmtp. I don't know of any such programs, but there probably are some.
