### ISSUE TITLE
msmtp as PHP mailer - is GPG+passwordeval the best choice here?

### ISSUE THREAD

**Issue by ohnonot** [marlam/msmtp-mirror#50]
First of all thank you for msmtp! I've been using ssmtp for way too long.

As the title says, I use it as a drop-in replacement for sendmail (mostly) to be used through a webpage's PHP contact form.

The logging into my mail account & sending of mail is performed by the www-data user without any user interaction.
To achieve this I created a key pair for www-data, with no passphrase. I did not succeed with a passphrase, because I found no way to enter the passphrase on the command line. GPG seems to simply ignore the --passphrase option.
This key pair is not used for anything else on this system.
Can this be considered sufficiently secure?
If not, what would be a better way to do it?
All "msmtp for PHP" tutorials I found simply store the password as plain text inside the config file...

I also tested an alternative that stores the password encrypted with openssl (using some environment variable as passphrase) but this doesn't work with Debian's msmtp-Apparmor profile, so there's a different challenge.

**Comment by marlam** [comment]
System-wide configurations with passwords can be problematic: any user that can run msmtp and can make it decrypt the password can then make it dump the password in clear text. So whatever method you use, you need to make sure that only www-data is able to decrypt the password, and that other users cannot assume the www-data identity.

**Comment by marlam** [comment]
I don't think I can help you with your GPG questions. They are probably better discussed elsewhere since they are not directly related to msmtp. I'll close this now, but feel free to reopen if there is need for further discussion.
