### ISSUE TITLE
support for DKIM?

### ISSUE THREAD

**Issue by rogers0** [marlam/msmtp-mirror#52]
I'm asking whether we can have DKIM support for msmtp?
I saw there's a post about this:
- https://stackoverflow.com/questions/63713214/how-to-use-msmtp-with-dkim-to-send-as-other-organisation

If it's possible to add some example config, it'd be appreciated.
Thanks!

**Comment by marlam** [comment]
The point of msmtp is to transport mails to the real full-featured MTA that takes care of such things.
I would say DKIM is outside the scope of msmtp.

**Comment by rogers0** [comment]
@marlam 
thanks for your feedback!

> The point of msmtp is to transport mails to the real full-featured MTA that takes care of such things.

From technical side, there's two implementation [1] needed to make it working:
- Signing an email, which msmtp may be related.
- Verification of an email, which usually occurs on MTA.

[1] https://en.wikipedia.org/wiki/DomainKeys_Identified_Mail

So what I requested for was the signing part.
Anyway, maybe there's way to use pipe in command line with msmtp, or msmtp can have one config to work with such command, just like ```passwordeval``` for password retrieving.

**Comment by marlam** [comment]
Maybe you can set up [OpenDKIM](http://opendkim.org/) as a filter before passing the mail to msmtp.
