### ISSUE TITLE
Installation error: gettext version 0.20 but the autoconf macros are from gettext version 0.19

### ISSUE THREAD

**Issue by andornaut** [marlam/msmtp-mirror#55]
I've been using [this Ansible role](https://github.com/andornaut/ansible-workstation/blob/master/roles/msmtp/tasks/main.yml#L31) to install MSMTP, but it started failing (it's been a while since I used it, though).

```
make[2]: Entering directory '/tmp/msmtp.git/po'
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.20 but the autoconf macros are from gettext version 0.19
```

Environment:
* Fresh install of Ubuntu server 20.04

### Workaround

Install [gettext v0.21 from Ubuntu hirsute](https://packages.ubuntu.com/hirsute/amd64/gettext/download)

**Comment by marlam** [comment]
This gettext problem comes up frequently. Unfortunately there is no way for msmtp to solve it. But you can work around it: either use a release archive of msmtp, or run `gettextize -f` (and maybe clean up some of the mess it makes) to force the use of your system gettext version.
