### ISSUE TITLE
msmtp with Duo/Outlook

### ISSUE THREAD

**Issue by mgree** [marlam/msmtp-mirror#57]
I've been having trouble getting msmtp to work with Duo/Outlook 365---I get EX_NOPERM. My IT department is unwilling to issue an app password, and the approach from #28 doesn't seem to port over, as Duo doesn't support OAuth2.

Does anyone have any experience with this? (Apologies if this is the wrong venue to ask.)

**Comment by marlam** [comment]
Since there was not enough information to find out what the problem might be, I'm closing this now.

**Comment by mgree** [comment]
It remains an issue for me, and I would be happy to try to debug it together. (I understand if this isn't something you want to work, on though.)

**Comment by marlam** [comment]
If this remains a problem, then I will try to fix it. The difficulty is that I don't use these services myself, so I need your help debugging. First of all, I thought these Microsoft services did support OAauth2? Is that not the case? What other option do you have then?

**Comment by mgree** [comment]
Amazing, thank you!

MS definitely supports OAuth2, but the last time I tried to use it with my employer's servers, it wasn't configured. They just switched from Duo to Okta, though, so maybe things will be better now?

Trying things again, Here's what I get so far:

```
msmtp: TLS handshake failed: An unexpected TLS packet was received.
msmtp: could not send mail (account stevens from /Users/mgree/.msmtprc)
ignoring system configuration file /usr/local/Cellar/msmtp/1.8.6/etc/msmtprc: No such file or directory
loaded user configuration file /Users/mgree/.msmtprc
using account stevens from /Users/mgree/.msmtprc
host = outlook.office365.com
port = 587
source ip = (not set)
proxy host = (not set)
proxy port = 0
timeout = off
protocol = smtp
domain = localhost
auth = choose
user = michael.greenberg@stevens.edu
password = *
passwordeval = cat /Users/mgree/.stevens.passwd
ntlmdomain = (not set)
tls = on
tls_starttls = off
tls_trust_file = system
tls_crl_file = (not set)
tls_fingerprint = (not set)
tls_key_file = (not set)
tls_cert_file = (not set)
tls_certcheck = on
tls_min_dh_prime_bits = (not set)
tls_priorities = (not set)
auto_from = off
maildomain = (not set)
from = michael.greenberg@stevens.edu
add_missing_from_header = on
add_missing_date_header = on
remove_bcc_headers = on
dsn_notify = (not set)
dsn_return = (not set)
logfile = /Users/mgree/.msmtp.log
logfile_time_format = (not set)
syslog = (not set)
aliases = (not set)
reading recipients from the command line
```

**Comment by marlam** [comment]
OK, the first thing is an easy fix: please use `tls_starttls on`.
That means the session does not immediately start with a TLS handshake, but instead uses the STARTTLS command within the session to initiate the TLS handshake.
SMTP on port 587 always requires STARTTLS; only connections on port 465 start directly with the TLS handshake.

**Comment by marlam** [comment]
The server tells you that it knows two authentication methods: 
```
$ msmtp -S --host=outlook.office365.com --port=587 --tls=on --tls-starttls=on
SMTP server at outlook.office365.com ([2603:1026:c0d:81a::2]), port 587:
[...]
    AUTH:
        Supported authentication methods:
        LOGIN XOAUTH2
```
The error message says that 'basic' authentication is disabled, which means the `LOGIN` method (although in that case they should not say that it is supported in response to the `EHLO` SMTP command, but that's another topic).
Which means you must use `auth xoauth2` in your configuration file, with the password set to your OAuth2 token.
How to get such a token depends on the service and I cannot help with that; msmtp merely passes it on to the server.

**Comment by mgree** [comment]
Okay, got it---so I'll try again with my admins and see if I can get OAuth working with our new 2FA provider. I'm closing the issue because it seems like Okta just has `xoauth2` working. Thank you for your help!
