### ISSUE TITLE
use environment variables/config file for msmtpq

### ISSUE THREAD

**Issue by xaltsc** [marlam/msmtp-mirror#58]
As says the `README`, for `msmtpq`: all config is done within the `msmtpq` script.

While this may be normal for a script, this is aberrant for something that is supposed to be distributed. Even though this script doesn't change that often, it's cumbersome having to watch for changes instead of letting the package manager do the work.

I may submit a PR in the near future since that doesn't seem to be that much work.

**Comment by marlam** [comment]
The script is intentionally not installed into a directory for executable files as in its current state it is just an example.
Also, the script is currently unmaintained so it seems unlikely that it will evolve into something that can be installed by default anytime soon.
