### ISSUE TITLE
msmtpd does not works with qBittorrent

### ISSUE THREAD

**Issue by CaringCat** [marlam/msmtp-mirror#59]
Hello,

I attempt to switch to msmtp, and use msmtpd as local smtp server. However so far I cannot get it working with qBittorrent.

My system is `Debian GNU/Linux 10 (buster) aarch64`, msmtp version 1.8.3, [qBittorrent EE v4.3.6.10](https://github.com/c0re100/qBittorrent-Enhanced-Edition).

qBittorrent has following config: 

```
[Preferences]
MailNotification\email=mail@example.com
MailNotification\enabled=true
MailNotification\password=
MailNotification\req_auth=false
MailNotification\req_ssl=false
MailNotification\sender=qBittorrent@service.example.com
MailNotification\smtp_server=localhost
MailNotification\username=
```

This works with both exim4 and opensmtpd as local smtp server, so probably isn't an issue from qBittorrent's side.

For `/etc/msmtprc`, I have:

```
# Set default values for all following accounts.
defaults
auth           on
tls            on
tls_starttls   off
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        /var/log/msmtp.log

# SendGrid
account        sendgrid
host           smtp.sendgrid.net
port           465
from           hostname@service.example.com
user           apikey
password       secrets

# Set a default account
account default : sendgrid
```

It works with [test email from Archwiki](https://wiki.archlinux.org/title/msmtp#Test_functionality), and apt-listchanges, so I guess that's also fine.

To run it as local smtp server, Debian provided the following systemd unit file:

```
[Unit]
Description=msmtp daemon
Documentation=man:msmtpd(1)

[Service]
DynamicUser=true
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
# NoNewPrivileges prevents the setgid mechanism from working
# so since msmtp is setgid in order to read /etc/msmtprc, the
# msmtp group need to be added in a different way
SupplementaryGroups=msmtp

Environment=INTERFACE=127.0.0.1 PORT=25
EnvironmentFile=-/etc/default/msmtpd

Type=simple
ExecStart=/usr/sbin/msmtpd --interface=${INTERFACE} --port=${PORT}

Restart=always
RestartSec=60

ProtectHome=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

And I can't get the notification at all. I checked the qBittorrent's log, and it doesn't give any useful info: 

```
(N) TIMESTAMP - 'Whatever' added to download list.
(N) TIMESTAMP - Torrent: Whatever Torrent, sending mail notification
```

And for msmtp's log, there is no new entry at all.

I have tried to bind msmtpd to `::1`, or change qBittorrent's config to `smtp_server=127.0.0.1`, no luck.

Do it happened to anyone else? How do I check if anything goes wrong? Thanks in advance.

Regards.

**Comment by marlam** [comment]
Looking at qBittorrent's source code shows that it does log errors if something goes wrong during the SMTP session, so if you have no such messages in your log we need to find another way of finding out what's going on.
Can you trigger qBittorrent to send some mail, and (temporarily) change the msmtpd command line with `--command=/path/to/dumpmail.sh` where the `dumpmail.sh` script looks like this:
```
#!/bin/bash                                                                                                                                                                                                                                                   
echo "$@" > ~/tmp/maildump                                                                                                                                                                                                                                    
cat >> ~/tmp/maildump
```
Then you should see 1) if msmtpd receives a mail from qBittorrent at all and 2) what the contents of the mail are (the first line of `/tmp/maildump` contains the full command line with all recipients, and the rest of the file contains the mail).

**Comment by CaringCat** [comment]
Thanks, and there is absolutely nothing in the `/tmp/maildump`.

I also tried 2 things:

1. Telnet to port 25 directly and [send a test email based on this example](https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol#SMTP_transport_example): Succeeded, Email dumped to `/tmp/maildump`.
2. Config qBittorrent to send via opensmtpd: Succeeded, Email get in my mailbox.
3. Config qBittorrent to send via msmtpd: Nothing, no maildump, no log.

Is there a super verbose debug mode?

**Comment by marlam** [comment]
msmtpd does not yet have logging, but I am preparing a patch to add this so that errors can be located easier.
However, I cannot reproduce the problem: I installed qBittorrent, configured it to send notifications to msmtpd, and it just works. I used qBittorrent 4.2.5 from Debian unstable for this test; maybe this matters?

**Comment by CaringCat** [comment]
I can also confirm that I cannot reproduce this problem is a Debian 11 Bullseye VM (amd64), with [qBittorrent EE v4.3.8.10 from this repo](https://github.com/c0re100/qBittorrent-Enhanced-Edition#debian-maintainer-kolcha) and msmtp version 1.8.11 from official repo. Yes, it just works as expected.

I will spin up a Debian 10 Buster VM and check if it fails.

**Comment by CaringCat** [comment]
I can reproduce this in `Debian GNU/Linux 10 (buster) x86_64`, msmtp version 1.8.3, [qBittorrent EE v4.3.8.10](https://github.com/c0re100/qBittorrent-Enhanced-Edition#debian-maintainer-kolcha).

I will raise this issue to Debian's bug tracking system.

**Comment by marlam** [comment]
I just compared `src/base/net/smtp.cpp` from qBittorrent 4.2.5 / Debian unstable and qBittorrent EE 4.3.8.10, but I cannot see any significant changes that would explain the difference in behavior.

**Comment by CaringCat** [comment]
> I just compared `src/base/net/smtp.cpp` from qBittorrent 4.2.5 / Debian unstable and qBittorrent EE 4.3.8.10, but I cannot see any significant changes that would explain the difference in behavior.

qBittorrent version doesn't matter here, I have tried  both `qBittorrent 4.1.5` and `qBittorrent EE v4.3.8.10` under Debian 10 Buster (oldstable) and they all failed. it will work in Debian 11 Bullseye with `msmtp Version 1.8.11`.

However install `msmtp version 1.8.11` from Buster Backports repo doesn't fix this issue, so I don't know if this is cause by an old version of msmtp, or by a dependency of it in Debian 10 Buster

**Comment by marlam** [comment]
OK, I know what's going on.

1.8.11 in Bullseye includes a cherry-picked patch that makes msmtpd accept lowercase SMTP commands, as allowed by the RFCs. The 1.8.11 backport for buster does not include that extra patch. And qBittorrent sends lowercase SMTP commands.(Though I am still not sure why qBittorrent does not report the failure of the SMTP session.)

The buster-backports version should probably be updated to include everything that the version in bullseye has.

In any case, I pushed the patch for `msmtpd` that adds options `--log` and `--log-level`, so in the future it will be easier to debug problems like this.

**Comment by CaringCat** [comment]
Thank you very much, I will update Debian report accordingly.
