### ISSUE TITLE
alias file replacement issue 

### ISSUE THREAD

**Issue by DirkNie** [marlam/msmtp-mirror#65]
Hallo Martin,
I try to use the msmtp on my Raspberry Nexcloud in version:
msmtp Version 1.8.3
Plattform: aarch64-unknown-linux-gnu

My problem is, that it seems not working to replace the local users eMail addresses via the aliases file configuration. The log output is like following when I send a local mail to an local user:
Jan 10 18:03:42 host=mail.gmx.net tls=on auth=on user=xxxxxx@gmx.de from=xxxxxx@gmx.de recipients=root@nextcloudpi smtpstatus=550 smtpmsg='550-Requested action not taken: mailbox unavailable\n550 invalid DNS MX or A/AAAA resource record' errormsg='Empfängeradresse root@nextcloudpi wird vom Server nicht akzeptiert' exitcode=EX_DATAERR

The "recipients=root@nextcloudpi" should normaly replaces by the entry from /etc/aliases. Here I have an entry for "default:".
In my msmtprc config is the aliases entry to /etc/aliases in the default configuration part. 

TIA
  Dirk

**Comment by marlam** [comment]
I cannot reproduce the problem, can you give the output of `--debug` or similar, so that I have a better chance of seeing what is going on?

**Comment by DirkNie** [comment]
Hello Martin,
I think I solved the problem with updating to the latest version from Github and I switched from GMX to Gmail SMTP hub.
GMX does not accept mails from my Raspberry OS cron configuration with Nextcloud installation. But Gmail works now.
THX
