### ISSUE TITLE
Local delivery without a daemon?

### ISSUE THREAD

**Issue by jaybeers** [marlam/msmtp-mirror#66]
Is it possible (or could it be made possible) to deliver mail to local accounts without requiring a persistent daemon (such as msmtpd or xinetd)?  Currently, it looks like msmtp by itself (i.e. without msmtpd) will deliver local mail (e.g. from cron) to the same smarthost as everything else, which (in my case) causes it to just get discarded.  (I'm currently using ssmtp, but it doesn't address this issue so I'm looking to switch.)

To put it another way: could msmtp detect mail to local recipients, and when it finds one, invoke `msmtpd --inetd` with stdin/stdout connected directly to msmtp to for local delivery (or just have msmtp itself do the delivery, but I'm guessing there are issues like file locking that only msmtpd knows how to deal with)?  To be clear: at no point am I looking to accept mail from outside the system.  This is strictly for mail originating on the box, to be sent to a local user, which is now getting lost because it gets sent to a smarthost and discarded at that point.

Ideally, it'd be nice to be able to provide a list of hostnames so that local delivery gets invoked for the following recipients:

- `user`
- `user@localhost`
- `user@mydomain.local.lan` <- user-provided arbitrary private domain
- `user@host.mydomain.local.lan` <- this host, on the private domain

At a minimum, catching `localhost` and the output of `hostname` and `hostname -f` would provide a generic solution for my use case and probably a lot of others' as well.

On the other hand, if I'm misreading msmtp and it's not designed to do any kind of final delivery at all, my apologies; I may be jumping the gun here after seeing msmtpd.  I don't see any _specific_ references to local delivery, but I'm hoping it's implied.  :)

**Comment by jaybeers** [comment]
I guess another solution might be that whenever you find an email that would be delivered locally (based on the above heuristic, for example) you deliver it as follows:

1. Capture the contents of the recipient header
2. Append a new header (`X-Original-Recipient` or something) with those contents
3. Replace the recipient with an arbitrary value (the user's public email address, as provided by the user)
4. Send it to the smarthost with everything else, at which point it would get delivered since it has a valid recipient

I dunno, seems like I'm stepping way out of the scope of this program now.  It just seems like I can't be the first person whose email needs are "local mail delivered locally, everything else to a smarthost".  :)

**Comment by marlam** [comment]
This is indeed outside the scope of msmtp. It is probably possible to craft some solution using scripts, but if you need local delivery I would really recommend installing postfix.

**Comment by jaybeers** [comment]
Mmm, yeah...the more I thought about it, the more I kinda figured that'd be the response.  Ah well, thanks for looking into it!
