### ISSUE TITLE
the server sent an invalid reply

### ISSUE THREAD

**Issue by UMFJoe** [marlam/msmtp-mirror#67]
just moved our email from a selfhosted imap to o365, and i switched all the setting over, based on the smtp auth instructions from msft, and enabled SMTP auth. o365 admin shows the user as having logged in sucessfully, but emails do not work. log gives

`
Mar 07 15:10:17 host=smtp.office365.com tls=on auth=on user=<redacted> from=<redacted> recipients=<redacted> errormsg='the server sent an invalid reply' exitcode=EX_PROTOCOL
`
below are the account settings. nothign defined in default except the log. 
```
account default
host smtp.office365.com
port 587
tls on
tls_starttls on
auth on
user 
password 
from 

```

**Comment by UMFJoe** [comment]
I switched to use the relay connector.  But i can probably set one up to test.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by marlam** [comment]
Since there was no further information, I'm closing this issue now.
