### ISSUE TITLE
Add config option to automatically add host/doman to RCPT TO

### ISSUE THREAD

**Issue by christgau** [marlam/msmtp-mirror#7]
Hi,

I used to use sSMTP on most of my systems to get local mail from tools like logcheck delivered to my mail server. Now, on a newly installed Debian system, I'd like to use msmtp as a [replacement for sSMTP](https://wiki.debian.org/sSMTP) since [it is currently not maintained](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925056). I had no problems when configuring mstmp for my mail server and delivery works without problems when I send mail from the command line with full recipient addresses, i.e. those that contain a domain name. 

However tools like logcheck (appear to) just send mail to local users without a domain name. With sSMTP, the `RewriteDomain` configuration value was appended to recipient used in smtp's RCPT TO command:

```
ssmtp-machine $ mailx -v root
Subject: test
test
.
Cc:
[<-] 220 mailserver.example.com ESMTP Exim 
[->] HELO myhost.example.com
[<-] 250 mailserver.example.com Hello public-hostname.example.com [ipv6-address]
[->] MAIL FROM:<user@myhost.example.com>
[<-] 250 OK
[->] RCPT TO:<root@myhost.example.com>
[<-] 250 Accepted
[->] DATA
[<-] 354 Enter message, ending with "." on a line by itself
...
[->] To: root
[->] Subject: test
...
[<-] 250 OKid=foobar
[->] QUIT
[<-] 221 mailserver.example.com  closing connection
```

With msmtp I was not able to configure it that way. If I perform the same steps as above I end with the following
```
msmtp-machine $ mailx -v root
Subject: test
test
.
Cc:
<-- 220 mailserver.example.com ESMTP Exim
--> EHLO my_other_host.example.com
<-- 250-mailserver.example.com Hello public-hostname.example.com [ipv6-address]
<-- 250-SIZE 52428800
<-- 250-8BITMIME
<-- 250-PIPELINING
<-- 250-AUTH PLAIN
<-- 250 HELP
--> MAIL FROM:<root@my_other_host.example.com>
--> RCPT TO:<root>
--> DATA
<-- 250 OK
<-- 501 <root>: recipient address must contain a domain
```

Maybe I missed something in the documentation, but It appears that I could only adjust the aliases file to achieve this. This appears cumbersome to do this configuration for every local (system) account that mail is potentially sent to. 

If there is no other way to do so currently, I'd like to suggest an option to append a domain name to the recipient that is passed to the mail server. Maybe something like `rcpt_to_domain` in the config file that adds '@' plus the configured value to the recipient(s) during SMTP exchange when no domain name is already present in the recipient address.

**Comment by marlam** [comment]
You can use the `aliases` command to specify an aliases file, e.g. `/etc/aliases`. This can replace local mail addresses (those without `@`). You can also specify a default alias for all local addresses. See the [list of commands for sendmail mode](https://marlam.de/msmtp/msmtp.html#Commands-specific-to-sendmail-mode).

Does this solve the problem?

**Comment by christgau** [comment]
Thanks. The default alias is what I was looking for and missed it in the docs.
