### ISSUE TITLE
msmtp + pass

### ISSUE THREAD

**Issue by tetumetal** [marlam/msmtp-mirror#70]
Dear msmtp users,

I'm using msmtp + pass by adding this line to the `.msmtprc`:
`     passwordeval "pass some_key_name"`

It's works fine if pass was unlocked previously. But, it fails if pass needs to invoke its cli to unlock the password. In that case I get the following error:
`gpg: decryption failed: No secret key`

Have anyone encounter this issue?

P.S.: I'm using msmtp version 1.8.16 and pass version 1.7.4

   Tetu,

**Comment by aabacchus** [comment]
Try putting `export GPG_TTY=$(tty)` in your `~/.shrc` or whatever your `$ENV` is.

**Comment by tetumetal** [comment]
It worked like a charm!, thanks a lot
