### ISSUE TITLE
[REQUEST] Hide host, user in config

### ISSUE THREAD

**Issue by minikN** [marlam/msmtp-mirror#73]
Hello,

I recently faced a situation where I set up a work email account which had out of the ordinary credentials (`user` wasn't the same as email and `host` was very specific as well. my msmtp config is part of my dotfiles, but I don't want to share information like this publicly. We have `passwordeval` for hiding passwords, would it be possible to implement something similar for `host` and `user`, like `hosteval` and `usereval`?

It could function exactly the same, as in it would just expect a command to be executed.

Thanks in advance.

**Comment by minikN** [comment]
> Maybe a general solution would be the cleanest option. Two ideas:
> 
> 1. For every command `cmd`, there would be a corresponding command `eval cmd` that works like `passwordeval` currently works. The existing function to read passwords would be modified to read any command argument. A drawback is that you have to maintain multiple files, one for each setting.
> 2. An new `eval` command includes the output of the given command into the current configuration. So you can put multiple settings into a single encrypted file, or even have a script generate them. A drawback is that an encrypted file would have to contain msmtp configuration commands instead of just values.
> 
> I think I would like option 2 better. What do you think?

I actually like both options. `1.` seems to be more modular while `2.` seems easier to implement.
In my specific case, I use `pass` to store my mail password. the encrypted file currently only contains the password, but ideally I'd rewrite it like so:

```
<password>
user: <username>
host: <host>
port: <port>
```
> A drawback is that you have to maintain multiple files, one for each setting.

I'm not sure but I think `pass` offers the ability to retrieve certain fields from config files, but even if it doesn't it should be trivial to write wrapper functions for this using the `pass show` command. Then I would add something like

```
...
passwordeval pass show path/to/mail/settings
hosteval func-to-retrieve-host-from-enc-file
usereval func-to-retrieve-user-from-enc-file
...
```
At least this is how I imagined it, but its tailored to my use case and others might differ. But then again, I like `2.` as well. If I understood correctly, you would make it abstract, so that it could be used with just the fields that I need (like user and host)?

Yeah, that works too I guess.

**Comment by marlam** [comment]
I revisited this issue today and found that both options would require substantial changes to the way msmtp handles configuration files, which seems a bit too much for a feature that will likely only be used in a few special cases.
I therefore went for a simplified version of option 2: a new `eval` command replaces the current line in the configuration file with the first line of the output of a given command. So no multi-line / multi-setting evaluation, but via scripts this is still pretty flexible, and the implementation was straightforward and did not require rewriting large parts of code in the middle of the stable 1.8.x series.
The changes are in the git repository (it might take a while before they hit the Github mirror though); can you check if this works for your use case?

**Comment by marlam** [comment]
This change is now in version 1.8.21.
