### ISSUE TITLE
Can msmtpd be configured to use a fixed account to run?

### ISSUE THREAD

**Issue by raidenii** [marlam/msmtp-mirror#75]
Hi,

I am trying to use msmtp-mta as a replacement for OpenSMTPD, given its capability of authenticating with Gmail via OAuth2. I wrote my own bash script to obtain OAuth2 token, and store client id, client secret, refresh token, etc in a json config file that is only readable by `msmtp` user, which is the account I run `msmtpd` as. `/etc/msmtprc` is configured to run the script to obtain token.

Everything works great if the sender is from other machine on the network, or root from localhost. However, if a local user other than root (i.e., does not have the permissions to read the json file) tries to send a mail (e.g, run something like `echo "test" | mail -s "test" user@example.org` from localhost), msmtp will fail to send mails since the user runs the command can't read the json file, thus the script obtaining access token will fail.

Is it possible to make msmtpd that when running as a service, it will not try to impersonate as the user issuing the send mail command, but just run as itself?

Thanks.

**Comment by marlam** [comment]
I think msmtpd is not impersonating the user, but that the `mail` command calls msmtp directly and does not go through msmtpd. Can you check this?

**Comment by marlam** [comment]
Since there was no reply, I'm closing this now.
