### ISSUE TITLE
Corrupted files that have embedded image in the body

### ISSUE THREAD

**Issue by marcelolaia** [marlam/msmtp-mirror#76]
I got trouble to send file that have image in the body. Both, pdf, odt and docx files that have embedded image are corrupted after transmission by msmtp.

More details in [this thread](http://lists.mutt.org/pipermail/mutt-users/Week-of-Mon-20220516/003496.html) or in [thats one](https://lists.debian.org/debian-user/2022/05/msg00655.html).

**Comment by marlam** [comment]
msmtp does not alter the contents of the mail body in any way.

The `--debug` option shows the full SMTP session so that you can compare original mail file and the data that is sent by msmtp. If you find a problem there, please reopen this issue.

**Comment by marcelolaia** [comment]
OK, you are correct. I did more tests and found:
If I send a message using `tee >(lbdb-fetchaddr -a)|/usr/bin/msmtp -a gmail $@`, the attached file with embedded image got corrupted;
The same result is got with `tee >(lbdb-fetchaddr -a -c utf8)`;
If I send a message using `/usr/bin/msmtp -a gmail $@`, the attached file with embedded image got loaded correctly.
Have you some clue, here?
Thank you so much!
