### ISSUE TITLE
domain command using %H or %M in configuration file doesn't work

### ISSUE THREAD

**Issue by mikenri** [marlam/msmtp-mirror#77]
Version: 1.8.6
OS: Ubuntu 20.04 

Expected Behavior:

Adding domain %H  to the configuration should set the server name used in SMTP "helo" to to the value of the $HOSTNAME variable 
Adding domain %M to the configuration should set the server name used in SMTP "helo" to the contents of /etc/mailname 

Actual Behavior:

The "Helo" is literally sent as either %H or %M, it doesn't send the value of the $HOSTNAME variable or the contents of /etc/mailname in the SMTP session.

**Comment by marlam** [comment]
The `%H` and `%M` expansions for the `domain` command are available in msmtp 1.8.16 or later. They are not yet available in your version of msmtp.
