### ISSUE TITLE
Domain substitution not working

### ISSUE THREAD

**Issue by gareththered** [marlam/msmtp-mirror#78]
I'm using a simple config to send mail to my smarthost:

```
account internal
domain "%H"
host 172.27.15.5

account default : internal
```

Looking at the logs, I see that the substitution above isn't working - it simply sends `EHLO %H`.  I've tried double quotes as shown, single quotes, and no quoting.

Am I doing something wrong?

I should add that mail is being sent - it's just my OCD which wants to change EHLO from localhost.

**Comment by marlam** [comment]
Are you sure you have version >= 1.8.16? Before that, these substitution patterns were not yet supported. See also https://github.com/marlam/msmtp-mirror/issues/77.

**Comment by gareththered** [comment]
Unfortunately, I have version 1.8.11.

Sorry for the noise - I'll close this.
