### ISSUE TITLE
Empty `From:` leads to wrong parsing of next line

### ISSUE THREAD

**Issue by real-or-random** [marlam/msmtp-mirror#8]
When sending out emails with `-t` and headers like:
```
From:
To: foo@bar.example
CC: bar@foo.example 
```
the empty From line made smtp to ignore the To line and send `RCPT TO` only for the CC recipients.

Now I guess an empty From line is a mistake on the user side, so I'm not sure if this is a bug. But maybe the parsing or the error reporting could be improved here.

**Comment by marlam** [comment]
Hi, thanks for reporting this!
Yes, an empty From: header is wrong, but that is no excuse for msmtp to behave that way.
This patch fixes it in my tests: 
https://git.marlam.de/gitweb/?p=msmtp.git;a=commitdiff;h=d49d79fda665e2769c97d57a0dba61ca1ebdacb6

**Comment by real-or-random** [comment]
Thanks!
