### ISSUE TITLE
OAuth2 renewal, initial authorization

### ISSUE THREAD

**Issue by pdobsan** [marlam/msmtp-mirror#80]
Hey,

@marlam, thank you for msmtp, I am a long time happy user!

As OAuth2 is getting popular, even obligatory like with gmail, it is great that msmtp can use access tokens.

To provide the other two OAuth2 functionalities (token renewal, and initial  authorization) I wrote a small utility, [mailctl](https://github.com/pdobsan/mailctl). I thought you and msmtp users might be interested in it.

**Comment by marlam** [comment]
Thanks for sharing this info, but I'm not sure how best to communicate this to the users (unfortunately we don't have a mailing list anymore).
