### ISSUE TITLE
Missing symbol when building msmtp 1.8.21 with gsasl

### ISSUE THREAD

**Issue by jpalus** [marlam/msmtp-mirror#85]
Linking of `msmtp 1.8.21` fails for me:
```
mold: error: undefined symbol: md5_digest
>>> referenced by msgid.c
>>>               msgid.o:(create_msgid)
collect2: error: ld returned 1 exit status
```
That's because new `msgid.c` source relies on `md5_digest` function:
https://github.com/marlam/msmtp-mirror/blob/f144a9be87c4dfa7d3750a76e3f288de0d8a8253/src/msgid.c#L64
present in `md5_apps.c`:
https://github.com/marlam/msmtp-mirror/blob/f144a9be87c4dfa7d3750a76e3f288de0d8a8253/src/md5-apps.c#L77
but the latter is built conditionally -- excluded if `gsasl` is enabled:
https://github.com/marlam/msmtp-mirror/blob/f144a9be87c4dfa7d3750a76e3f288de0d8a8253/src/Makefile.am#L34-L37

**Comment by marlam** [comment]
Oops... sorry about that. This is fixed now in 1.8.22. Thanks for reporting this so fast.
