### ISSUE TITLE
msmtpq doesn’t work properly if `$Q` contains spaces

### ISSUE THREAD

**Issue by Jayman2000** [marlam/msmtp-mirror#87]
## Steps to reproduce

1. `mkdir -p ~/Spaces\ in\ path/Q`
2. `export Q=~/Spaces\ in\ path/Q`
3. Disconnect from the Internet (or do something else that will make `msmtpq` fail to send a message).
4. `printf 'Subject: Test subject\n\nTest Body.\n' | msmtpq <some-email-address>`
5. `msmtpq --q-mgmt -d`

That will tell you that there’s no messages in the queue, even though there’s supposed to be one in the queue.

**Comment by marlam** [comment]
Should be fixed now.
