### ISSUE TITLE
msmtp: no recipients found

### ISSUE THREAD

**Issue by Buadhai** [marlam/msmtp-mirror#91]
This on an M1 iMac [MacOS 12.5.1] running:

msmtp version 1.8.22
Platform: aarch64-apple-darwin21.3.0

The .msmtprc file on the Mac is essentially identical to the configuration file on a Raspberry Pi 4  [Raspberry Pi 4 Model B Rev 1.2) [Raspbian GNU/Linux 10 (buster)] running:

msmtp version 1.8.3
Platform: arm-unknown-linux-gnueabihf

msmtp runs fine on the Pi but fails with the following on the Mac:

**msmtp: no recipients found**
Sending data to /opt/local/bin/msmtp failed: Process exited with a non-zero status
cannot send message: Process exited with a non-zero status

Valentine:~ mnewman$ echo $?
1

**Comment by Buadhai** [comment]
Just for further information:

Valentine:~ mnewman$ msmtp --serverinfo
SMTP server at smtp.gmail.com (si-in-f108.1e100.net [172.217.194.108]), port 587:
    smtp.gmail.com ESMTP i15-20020a17090332cf00b0016dc6243bb2sm5752709plr.143 - gsmtp
TLS session parameters:
    (TLS1.3)-(ECDHE-X25519)-(ECDSA-SECP256R1-SHA256)-(AES-256-GCM)
TLS certificate information:
    Subject:
        CN=smtp.gmail.com
    Issuer:
        C=US,O=Google Trust Services LLC,CN=GTS CA 1C3
    Validity:
        Activation time: Mon Aug  1 15:24:33 2022
        Expiration time: Mon Oct 24 15:24:32 2022
    Fingerprints:
        SHA256: 91:B6:49:B0:8F:EB:B9:63:FA:6F:20:2E:09:C0:E5:29:E2:75:B9:25:01:58:B3:14:06:48:BD:6C:DB:90:BD:11
        SHA1 (deprecated): 4C:99:E0:7B:44:68:DE:06:25:3F:E3:A4:5F:10:93:83:52:8A:47:78
Capabilities:
    SIZE 35882577:
        Maximum message size is 35882577 bytes = 34.22 MiB
    PIPELINING:
        Support for command grouping for faster transmission
    STARTTLS:
        Support for TLS encryption via the STARTTLS command
    AUTH:
        Supported authentication methods:
        PLAIN LOGIN OAUTHBEARER XOAUTH2

**Comment by marlam** [comment]
Recipients must be either given on the command line, or the option `-t` must be used to read them from the mail.
This is unrelated to the server; it depends on how msmtp is called by the program or script that wants to send the mail.

**Comment by Buadhai** [comment]
This on the iMac where it fails:

```
Valentine:~ mnewman$ mail me@mac.com
Cc:
Subject: None
Done
msmtp: no recipients found
Sending data to /opt/local/bin/msmtp failed: Process exited with a non-zero status
cannot send message: Process exited with a non-zero status

```
This on a Raspberry Pi where it succeeds

```
pi@raspsky:~/webcam $ mail me@mac.com
Cc:
Subject: none
done

```

How should I change the way I'm sending mail on the iMac to make it work the way it does on the Raspberry Pi?

**Comment by marlam** [comment]
Please consult the documentation of the `mail` command. With some versions of `mail`, you can have a configuration file `~/.mailrc` that allows to configure something like `set sendmail=...`.

**Comment by Buadhai** [comment]
```
Valentine:~ mnewman$ cat .mailrc
set sendmail="/opt/local/bin/msmtp"
Valentine:~ mnewman$ which -a msmtp
/opt/local/bin/msmtp
```

**Comment by Buadhai** [comment]
I found the problem:

```
Valentine:~ mnewman$ which -a mail
/opt/local/bin/mail
/usr/bin/mail

```
The first one was installed with mailutils. The second one must come with the OS. I need to use the second one, but:

```
Valentine:~ mnewman$ type mail
mail is /opt/local/bin/mail

```

I tried to fix it like this:

```
Valentine:~ mnewman$ alias mail="/usr/bin/mail"
Valentine:~ mnewman$ type mail
mail is aliased to `/usr/bin/mail'
```

Not sure if that's the right way.
