### ISSUE TITLE
document that `eval` always runs, independent of account being used

### ISSUE THREAD

**Issue by m4lvin** [marlam/msmtp-mirror#94]
I happily used the new `eval` feature (thanks for that! :rocket:) and thereby ran into issue https://github.com/marlam/msmtp-mirror/issues/18 again :facepalm:

The surprise in my case was that I added `eval` in one `account` block but the problem of truncated attachments happened with another account :thinking: 

Maybe the documentation could clarify *when* and how often `eval` is run (once, and before doing anything else?) and that (as far as I understand) *all* the `eval` lines will be executed, even if the mail being sent will use a different account. (Which I guess has to be like this, given that an `eval` might influence the choice of account...)

**Comment by marlam** [comment]
I added a note that all `eval` commands are evaluated when a configuration file is read.
There already is a note that the command must not mess with `stdin`. The only real solution here is to replace `popen()` with something better, but low level, as in #18. That would also benefit `msmtpd` which also suffers from `popen()` problems...
