### ISSUE TITLE
AM_GNU_GETTEXT is used, but not AM_GNU_GETTEXT_VERSION

### ISSUE THREAD

**Issue by Maloupi** [marlam/msmtp-mirror#99]
Hi,
When running autoreconf -i, the following message is issued (Rocky 9 / Centos 9 / RHEL 9) :
`autoreconf: configure.ac: AM_GNU_GETTEXT is used, but not AM_GNU_GETTEXT_VERSION`
This does not block the install.

**Comment by marlam** [comment]
You can safely ignore this warning, it has no meaning or consequences.
